/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getEngineInfo(): string
/** Convenience function to check if an FHIRPath expression returns any results */
export declare function exists(expression: string, resource: string): boolean
export declare class FhirPathEngine {
  constructor()
  /** Evaluates an FHIRPath expression against a FHIR resource (synchronous) */
  evaluate(expression: string, resource: string): string
  /**
   * Evaluates an FHIRPath expression against a FHIR resource (asynchronous)
   * Uses a thread pool for CPU-bound operations to avoid blocking the event loop
   */
  evaluateAsync(expression: string, resource: string): Promise<string>
  /** Validates a FHIRPath expression syntax */
  validate(expression: string): boolean
  /** Returns the version of the FHIRPath engine */
  version(): string
}
